-- MySQL 8.0+
CREATE TABLE IF NOT EXISTS users (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	telegram_id BIGINT NOT NULL UNIQUE,
	username VARCHAR(64) NULL,
	first_name VARCHAR(128) NULL,
	last_name VARCHAR(128) NULL,
	language_code VARCHAR(8) NULL,
	points INT NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS referrals (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	inviter_user_id BIGINT UNSIGNED NOT NULL,
	invitee_user_id BIGINT UNSIGNED NOT NULL,
	status ENUM('pending','qualified','revoked') NOT NULL DEFAULT 'pending',
	qualified_at TIMESTAMP NULL,
	revoked_at TIMESTAMP NULL,
	UNIQUE KEY uniq_ref_pair (inviter_user_id, invitee_user_id),
	FOREIGN KEY (inviter_user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (invitee_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS points_transactions (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	amount INT NOT NULL,
	type ENUM('referral_reward','spend','revoke','adjust') NOT NULL,
	reference_id BIGINT NULL,
	description VARCHAR(255) NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	INDEX idx_user_created (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS items (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	required_points INT NOT NULL,
	is_active TINYINT(1) NOT NULL DEFAULT 1,
	priority INT NOT NULL DEFAULT 0,
	stock INT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	item_id BIGINT UNSIGNED NOT NULL,
	status ENUM('pending','under_review','approved','rejected') NOT NULL DEFAULT 'pending',
	note VARCHAR(255) NULL,
	admin_id BIGINT UNSIGNED NULL,
	admin_message_id BIGINT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admins (
	user_id BIGINT UNSIGNED PRIMARY KEY,
	role ENUM('owner','admin') NOT NULL DEFAULT 'admin',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS forced_channels (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	channel_id VARCHAR(64) NOT NULL,
	title VARCHAR(128) NULL,
	is_required TINYINT(1) NOT NULL DEFAULT 1,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
	`key` VARCHAR(64) PRIMARY KEY,
	`value` VARCHAR(255) NOT NULL,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;